package ru.kharevich.userservice.model;

public enum UserModifyEventType {
    CREATE_EVENT, UPDATE_EVENT, DELETE_EVENT,
    CREATE_COMPENSATION_EVENT, UPDATE_COMPENSATION_EVENT, DELETE_COMPENSATION_EVENT,
}
