server:
  port: 8020
spring:
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://${keycloak.domain}:8080/realms/${keycloak.realm}"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/user_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  config:
    time_of_expiration_of_accounts_in_days: 30
    period_of_user_cleaning_in_millis: 3600000

#keycloak:
#  domain: localhost
#  clientId: client-api
#  clientSecret: BZfd81ImCiMvyNG1yCDj8irt4VDENVUJ
#  auth-url:  http://${keycloak.domain}:8080
#  realm: chat-realm
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          - health
#          - prometheus
#  prometheus:
#    metrics:
#      export:
#        enabled: true
#  metrics:
#    tags:
#      application: authentication-service
#  zipkin:
#    tracing:
#      endpoint: ${TEMPO_ZIPKIN_URL:http://localhost:9411/api/v2/spans}
#  tracing:
#    sampling:
#      probability: 1.0