server:
  port: 8010
spring:
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/chat?authSource=admin
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
management:
  zipkin:
    tracing:
      endpoint: ${TEMPO_ZIPKIN_URL:http://localhost:9411/api/v2/spans}
