server:
  port: 8010
spring:
  application:
    name:
      chat-service
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/chat?authSource=admin
      auto-index-creation: true

