server:
  port: 8010
spring:
  application:
    name:
      chat-service
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/chat?authSource=admin
      auto-index-creation: true
  kafka:
    topic:
      message: message-topic
    producer:
      bootstrap-server: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      observation-enabled: true
      properties:
        spring.json.type.mapping: messageRequest:ru.kharevich.chatservice.dto.request.MessageRequest
    consumer:
      bootstrap-servers: localhost:9092
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      observation-enabled: true
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: messageRequest:ru.kharevich.chatservice.dto.request.MessageRequest
